apiVersion: apps/v1
kind: Deployment
metadata:
  name: linqra-backend
  namespace: linqra
  labels:
    app: linqra-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: linqra-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: linqra-backend
    spec:
      containers:
        - name: api-gateway
          image: 945104357909.dkr.ecr.us-west-2.amazonaws.com/linqra-backend:latest
          ports:
            - containerPort: 7777
          env:
            - name: VAULT_ENVIRONMENT
              value: "ec2"
            - name: VAULT_REQUIRED_VARS
              value: "SPRING_PROFILES_ACTIVE,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,GATEWAY_TRUSTSTORE_PASSWORD"
            # Inject Master Key from K8s Secret
            - name: VAULT_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: linqra-vault-secret
                  key: master-key
            # Correct SSO Redirect URI for EKS (Override Vault)
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_LINQRA_GATEWAY_CLIENT_REDIRECT_URI
              value: "https://linqra.com/callback"
            # Temporary: Disable Redis Listener to prevent crash (VPC Mismatch)
            - name: APP_REDIS_LISTENER_ENABLED
              value: "false"
          volumeMounts:
            # Mount the vault file
            - name: vault-volume
              mountPath: /app/secrets
              readOnly: true
          livenessProbe:
            tcpSocket:
              port: 7777
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: 7777
            initialDelaySeconds: 45
            periodSeconds: 15
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
      volumes:
        - name: vault-volume
          secret:
            secretName: linqra-vault-secret
            items:
              - key: vault-file
                path: vault.encrypted
---
apiVersion: v1
kind: Service
metadata:
  name: linqra-backend-service
  namespace: linqra
spec:
  type: NodePort
  selector:
    app: linqra-backend
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
