package org.lite.gateway.enums;

/**
 * Enumeration of audit event types for tracking system activities
 */
public enum AuditEventType {
    // Data Access Events
    DOCUMENT_ACCESSED,
    DOCUMENT_VIEWED,
    CHUNK_ACCESSED,
    CHUNK_DECRYPTED,
    METADATA_ACCESSED,
    GRAPH_ENTITY_ACCESSED,
    GRAPH_RELATIONSHIP_ACCESSED,
    RAG_QUERY,
    VECTOR_SEARCH,
    
    // RAG/Vector Collection Events
    RAG_COLLECTION_CREATED,
    RAG_COLLECTION_DELETED,
    RAG_COLLECTION_UPDATED,
    
    // Data Modification Events
    DOCUMENT_UPLOADED,
    DOCUMENT_PROCESSING_STARTED,
    DOCUMENT_PROCESSING_COMPLETED,
    DOCUMENT_PROCESSING_FAILED,
    DOCUMENT_PROCESSING_SKIPPED,
    DOCUMENT_DELETED,
    DOCUMENT_HARD_DELETED,
    CHUNK_CREATED,
    CHUNK_DELETED,
    METADATA_EXTRACTED,
    METADATA_UPDATED,
    METADATA_DELETED,
    GRAPH_EXTRACTION_STARTED,
    GRAPH_EXTRACTION_COMPLETED,
    GRAPH_ENTITY_CREATED,
    GRAPH_ENTITY_DELETED,
    GRAPH_RELATIONSHIP_CREATED,
    GRAPH_RELATIONSHIP_DELETED,
    
    // Data Export Events
    EXPORT_INITIATED,
    EXPORT_COMPLETED,
    EXPORT_FAILED,
    EXPORT_DOWNLOADED,
    
    // Authentication & Authorization Events
    USER_LOGIN,
    USER_LOGOUT,
    LOGIN_FAILED,
    TOKEN_REFRESHED,
    ROLE_CHANGED,
    PERMISSION_MODIFIED,
    TEAM_SWITCHED,
    
    // Security Events
    ACCESS_DENIED,
    UNAUTHORIZED_ACCESS_ATTEMPT,
    DECRYPTION_FAILED,
    ENCRYPTION_FAILED,
    VAULT_ACCESSED,
    KEY_ROTATION_STARTED,
    KEY_ROTATION_COMPLETED,
    PII_DETECTED,
    
    // Administrative Actions
    USER_CREATED,
    USER_DELETED,
    USER_UPDATED,
    TEAM_CREATED,
    TEAM_UPDATED,
    TEAM_DELETED,
    COLLECTION_CREATED,
    COLLECTION_DELETED,
    COLLECTION_UPDATED,
    API_ROUTE_CREATED,
    API_ROUTE_UPDATED,
    API_ROUTE_DELETED,
    CONFIGURATION_CHANGED,
    
    // Agent & Workflow Events
    AGENT_TASK_EXECUTION_STARTED,
    AGENT_TASK_EXECUTION_COMPLETED,
    AGENT_TASK_EXECUTION_FAILED,
    WORKFLOW_EXECUTION_STARTED,
    WORKFLOW_EXECUTION_COMPLETED,
    WORKFLOW_EXECUTION_FAILED,
    WORKFLOW_STEP_EXECUTED,
    
    // LLM Events
    LLM_REQUEST_STARTED,
    LLM_REQUEST_COMPLETED,
    LLM_REQUEST_FAILED,
    CHAT_EXECUTION_STARTED,
    CHAT_EXECUTION_COMPLETED,
    CHAT_EXECUTION_FAILED,
    
    // System Events
    ARCHIVAL_STARTED,
    ARCHIVAL_COMPLETED,
    ARCHIVAL_FAILED,
    BACKUP_CREATED,
    BACKUP_RESTORED
}

